server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=booking_db;encrypt=false;user=sa;password=Password_123
  jpa:
    hibernate:
      ddl-auto: update

service:
  people:
    url: http://localhost:8081/api/v1/people/person/
