spring.application.name=crud.demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=TODO;encrypt=false;user=sa;password=P@ssw0rd

#spring.main.banner-mode=off

logging.level.root=warn

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
#spring.jpa.hibernate.ddl.auto=create








