spring.application.name=aopdemo

#spring banner off
spring.main.banner-mode=off

#reduce logging level
logging.level.root=warn

#enable debug logging for aop
logging.level.org.springframework.aop=DEBUG