spring.application.name=Springdemo
management.endpoints.web.exposure.iclude=health,info
management.endpoints.web.exposure.exclude=health,info
#management.endpoints.web.exposure.include=*

#management.info,env.enabled=true
info.app.name=MY APP
info.app.description=yoohoo!
info.app.version=1.0.0
coach.name =borhane
team.name =nejmeh
