spring.application.name=administration

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=booking_db;encrypt=false;user=sa;password=Password_123
spring.jpa.hibernate.ddl-auto=update

server.port=8081