spring.application.name=springbootapp

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=employee_directory;encrypt=false;user=sa;password=yourStrong(!)Password
spring.jpa.hibernate.ddl-auto=update

#turning off spring boot banner
spring.main.banner-mode=off

#reducing logging level
logging.level.root=warn
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

#spring data rest properties
spring.data.rest.base-path=/magic-api
spring.data.rest.default-page-size=20