spring.application.name=walletExercicedemo
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=UserServiceDB;encrypt=false;user=sa;password=P@ssw0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=true
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA and Hibernate properties


spring.jpa.show-sql=true
# UserService URL (can be dynamic depending on environment)
user.service.url=http://localhost:8080/users

# TransactionService URL (can be dynamic depending on environment)
transaction.service.url=http://localhost:8081/transactions

# Enable debug logging for Spring Security
logging.level.org.springframework.security=DEBUG

# Enable info logging for other Spring Boot related activities
logging.level.org.springframework.boot=INFO



