spring.application.name=cruddemo
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=employee_directory;encrypt=false;user=sa;password=P@ssw0rd
#turn off the spring boot banner
#spring.main.banner-mode=off
#reduce logging level . sef logging level to warn
logging.level.root=warn
spring.jpa.open-in-view=true

#show JPA/Hibernate logging messages
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace
