spring.application.name=TransactionServicedemo
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=TransactionServiceDB;encrypt=false;user=sa;password=P@ssw0rd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=true
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA and Hibernate properties
server.port=8081
#import com.example.walletExercicedemo.service.UserService;

spring.jpa.show-sql=true
# UserService URL for TransactionService to call (can be dynamic)
user.service.url=http://localhost:8080/users


